---
- name: Configure the database server
  hosts: db
  become: yes
  tasks:
    - name: Install MySQL server
      yum:
        name: mysql-server
        state: present

    - name: Start MySQL service
      service:
        name: mysqld
        state: started
        enabled: true

    - name: Create a database
      mysql_db:
        name: example_db
        state: present

    - name: Create a user with privileges
      mysql_user:
        name: example_user
        password: example_password
        priv: '*.*:ALL'
        state: present
