pipeline {
    agent any

    environment {
        ANSIBLE_CONFIG = "${WORKSPACE}/deploy/ansible.cfg"
    }

    parameters {
        string(
            name: 'inventory', 
            defaultValue: 'dev',  
            description: 'This is the inventory file for the environment to deploy configuration'
        )
    }

    stages {
        stage("Initial Cleanup") {
            steps {
                deleteDir() // Deletes everything in the current workspace
            }
        }

        stage('Checkout SCM') {
            steps {
                git branch: 'feature/jenkinspipeline-stages', url: 'https://github.com/Ayomipohub/ansible-config.git'
            }
        }

        stage('Prepare Ansible For Execution') {
            steps {
                sh 'echo ${WORKSPACE}'
                sh '''
                    grep -qxF "roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg || echo "roles_path=${WORKSPACE}/roles" >> ${WORKSPACE}/deploy/ansible.cfg
                '''
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                ansiblePlaybook(
                    become: true, 
                    colorized: true, 
                    credentialsId: 'ayo-key', 
                    disableHostKeyChecking: true, 
                    installation: 'ansible', 
                    inventory: "inventory/${params.inventory}", 
                    playbook: 'playbooks/site.yml', 
                    vaultTmpPath: ''
                )
            }
        }

        stage('Clean Workspace After Build') {
            steps {
                cleanWs(
                    cleanWhenAborted: true, 
                    cleanWhenFailure: true, 
                    cleanWhenNotBuilt: true, 
                    cleanWhenUnstable: true, 
                    deleteDirs: true
                )
            }
        }
    }
}
