---
- name: Loadbalancers assignment
  hosts: lb
  when: load_balancer_is_required
  tasks:
    - import_playbook: ../static-assignments/loadbalancers.yml

    


#- import_playbook: ../static-assignments/common-del.yml


#- name: uat-webservers assignment
#- import_playbook: ../static-assignments/uat-webservers.yml