---
- name: artifactory assignment
  hosts: artifactory
  become: true
  tasks:
    - name: Import Artifactory Playbook
      ansible.builtin.include_tasks: "../static-assignments/artifactory.yml"


#- name: Database Playbook
 # hosts: db
  #become: true
  #tasks:
   # - name: Include database tasks
    #  ansible.builtin.import_tasks: "../static-assignments/db.yml"

#- name: NGINX Playbook
 # hosts: nginx
  #become: true
  #tasks:
   # - name: Include nginx tasks
    #  ansible.builtin.import_tasks: "../static-assignments/nginx.yml"



#- name: Loadbalancers assignment
 # import_playbook: ../static-assignments/loadbalancers.yml
  #when: load_balancer_is_required


#- import_playbook: ../static-assignments/common-del.yml


#- name: uat-webservers assignment
#- import_playbook: ../static-assignments/uat-webservers.yml