---
#- name: Loadbalancers assignment
 # hosts: lb
  #tasks:
    #- import_playbook: ../static-assignments/loadbalancers.yml
      #when: load_balancer_is_required

---
- hosts: all
- name: Include dynamic variables
  #tasks:
  #import_playbook: ../static-assignments/common.yml
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always
- hosts: lb
- name: Loadbalancers assignment
  import_playbook: ../static-assignments/nginx-lb.yml
  when: load_balancer_is_required


#- import_playbook: ../static-assignments/common-del.yml


#- name: uat-webservers assignment
#- import_playbook: ../static-assignments/uat-webservers.yml