---
- name: Database Playbook
  hosts: db
  become: true
  tasks:
    - name: Include database playbook
      ansible.builtin.import_tasks: ../static-assignments/db.yml

- name: NGINX Playbook
  hosts: nginx
  become: true
  tasks:
    - name: Include nginx playbook
      ansible.builtin.import_tasks: ../static-assignments/nginx.yml


#- hosts: all
#- name: Include dynamic variables
  # include: ../dynamic-assignments/env-vars.yml
  #tags:
   # - always
#- hosts: lb
#- name: Loadbalancers assignment
 # import_playbook: ../static-assignments/loadbalancers.yml
  #when: load_balancer_is_required


#- import_playbook: ../static-assignments/common-del.yml


#- name: uat-webservers assignment
#- import_playbook: ../static-assignments/uat-webservers.yml