---
- name: import common file
  import_playbook: ../static-assignments/loadbalancers.yml
  tags:
	  - always

- name: includes env-vars file
  import_playbook: ../static-assignments/loadbalancers.yml
  tags:
	  - always

- name: import database file
  import_playbook: ../static-assignments/loadbalancers.yml
  
- name: import common file
  import_playbook: ../static-assignments/loadbalancers.yml
  tags:
	  - always

- name: import webservers file
  import_playbook: ../static-assignments/loadbalancers.yml
  
- name: Loadbalancers assignment
  hosts: lb
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required





#- import_playbook: ../static-assignments/common-del.yml


#- name: uat-webservers assignment
#- import_playbook: ../static-assignments/uat-webservers.yml